version: '3'
services:
  app:
    image: my-flask-app:latest # Replace with the image name you used when building your Flask application
    ports:
      - "4000:80"  # Map the Flask app's port to the host machine

  log_forwarder:
    image: log_forwarder_image:latest  # Replace with the image for your log forwarder
    volumes:
      - ./log_files:/logs  # Mount the directory with log files
    environment:
      - LOG_SOURCE=/logs
      - KIBANA_HOST=kibana-service  # Change this to the address of your Kibana service

# Define a network to allow the containers to communicate
networks:
  default:
    external:
      name: my_network  # Change this to an existing network name or create a new one
